services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    environment:
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro

  db:
    build: ./db
    ports:
      - 1433:1433
